upgrade the Rust toolchain due to compiler bugs
The rustc has been crashing with the following message on repeated
compilations:

    thread 'rustc' panicked at 'found unstable fingerprints for predicates_of(core[3998]::fmt::Debug)', /rustc/f5f33ec0e0455eefa72fc5567eb1280a4d5ee206/compiler/rustc_query_system/src/query/plumbing.rs:593:5
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

    error: internal compiler error: unexpected panic

    note: the compiler unexpectedly panicked. this is a bug.

    note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

    note: rustc 1.52.0-nightly (f5f33ec0e 2021-03-19) running on x86_64-unknown-linux-gnu

    note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type rlib --crate-type dylib

    note: some of the compiler flags provided by cargo are hidden

    query stack during panic:
    #0 [predicates_of] computing predicates of `std::fmt::Debug`
    #1 [object_safety_violations] determine object safety of trait `project::splitters::Splitter`
    end of query stack